_target_: src.models.resnet_module.EfficientNetModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
net:
  _target_: src.models.components.efficient_net_torchvision.EfficientNet
  num_classes: 2
  version: "v1"

criterion: "entropy"

# compile model for faster training with pytorch 2.0
compile: false
